version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /voxceleb
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /loss-landscape
    schedule:
      interval: monthly
