cuda: True
dataset: voxceleb
model: res2next6s8g
batch_size: 1200
threads: 8
x: '-0.35:0.35:8'
# y: '-0.35:0.35:8'
# x: '-0.3:0.3:7'
y: '-0.3:0.3:7'
#x: '-0.00001:0.00001:21'
#y: '-0.00001:0.00001:21'
model_file: voxceleb/trained_net/weights_om/Res2NeXt6s8g/Vox1-O/model000000130.model
dir_type: weights
xnorm: filter
xignore: biasbn
ynorm: filter
yignore: biasbn
plot: True
train_list: data/SpeakerDataVox2.hdf5
iter_stop: 15
out_dir: Output/resnext6s8g_train

# voxceleb parameters
trainfunc: aamsoftmax
nPerSpeaker: 1
n_mels: 80
nOut: 256
seed: 0
use_wandb: False
wandb_project: res2net6s8g
wandb_random_coords: 10
encoder_type: SAP
reduction: 12
log: True