model: ResNetSE34V2
log_input: True
encoder_type: ASP
trainfunc: aamsoftmax
save_path: exps/eval/ResNetSE34Lv2_AAMSoftmax
initial_model: /mnt/ssd2/Tassi/TassiMA/loss-landscape/voxceleb/trained_net/weights_om/ResNetSE34Lv2_AAMSoftmax/model000000008.model
nPerSpeaker: 1
batch_size: 400
n_mels: 64

wandb: False
max_frames: 400
nDataLoaderThread: 12
# train_list: /mnt/Games/Tassia_Daten/SpeakerDataVox1.hdf5

seed: 0
torch_seed: 0

eval: True
