"""
    Serialization and deserialization of directions in the direction file.
"""

import torch
from pptree import Node, print_tree
import h5py
import numpy as np
import shutil
import os
import re
import matplotlib.pyplot as plt

def write_list(f, name, direction):
    """ Save the direction to the hdf5 file with name as the key

        Args:
            f: h5py file object
            name: key name_surface_file
            direction: a list of tensors
    """

    grp = f.create_group(name)
    for i, l in enumerate(direction):
        if isinstance(l, torch.Tensor):
            l = l.numpy()
        grp.create_dataset(str(i), data=l)


def read_list(f, name):
    """ Read group with name as the key from the hdf5 file and return a list numpy vectors. """
    grp = f[name]
    return [grp[str(i)] for i in range(len(grp))]


def print_hdf5(file):
    """
    Print the structure of the hdf5 file

    Args:
        file (str): path to the hdf5 file
    """
    def traverse(stem, grp):
        for key in list(grp):

            if isinstance(grp[key], h5py.Group):
                thisnode = Node(key, stem)
                traverse(thisnode, grp[key])

            elif isinstance(grp[key], h5py.Dataset):
                thisnode = Node(f"{key} {str(grp[key].shape)} {str(grp[key].dtype)}", stem)
    print(f"File: {file}")
    root = Node('root')
    file = h5py.File(file, "r")
    traverse(root, file)
    print_tree(root)
    return ""


def create_surface_file_name(new_x, new_y=None, file_name=None):
    if new_y is not None :
        range_str = "[%.2f,%.2f,%d]x[%.2f,%.2f,%d]" % (new_x[0],new_x[-1],len(new_x),new_y[0],new_y[-1],len(new_y))
    else:  range_str = "[%.2f,%.2f,%d]" % (new_x[0],new_x[-1],len(new_x))
    if file_name is not None:
        file_name = re.sub(r"\[.+\]", range_str, file_name)
    else:
        file_name = "surface_" + range_str + ".hdf5"
    return file_name


class SurfaceFileHandler():
    """
    This class is used to handle the hdf5 files generated by the surface model.

    Args:
    - path (str): path to the hdf5 file

    Methods:
    - getDirFile: returns the directory of the file used to generate the hdf5 file
    - getCoordinates: returns the coordinates of the surface
    - getTrainLoss: returns the training loss
    - getTrainAcc: returns the training accuracy
    - __str__: prints the structure of the hdf5 file use print(SurfaceFileHandler) to print the structure
    """
    def __init__(self,path):
        self.f = h5py.File(path, "r")
        self.path = path

        assert "dir_file" in self.f.keys(), "dir_file not found in hdf5 file - this is not a valid surface file"  
        assert "xcoordinates" in self.f.keys(), "xcoordinates not found in hdf5 file - this is not a valid surface file"
        assert "train_loss" in self.f.keys(), "train_loss not found in hdf5 file - this is not a valid surface file"
        assert "train_acc" in self.f.keys(), "train_acc not found in hdf5 file - this is not a valid surface file"
        if self.is2D():
            assert "ycoordinates" in self.f.keys(), "ycoordinates not found in hdf5 file"
    
    # with this method print(SurfaceFileHandler) will print the structure of the hdf5 file
    def __str__(self):
        print_hdf5(self.path)
        # check if there are values exactly equal to -1 in the train_loss and train_acc
        if (self.getTrainAcc() == -1).any().item():
            print("!!!! Warning: this surface file was not fully calculated !!!!")
        return ""

    def getDirFile(self):
        return self.f["dir_file"][()].decode("utf-8")
    
    def getCoordinates(self):
        x = self.f["xcoordinates"][:] 
        # return ycoordinates if exists, otherwise return xcoordinates
        if "ycoordinates" in self.f:
            y = self.f["ycoordinates"][:]
            return {"x":x, "y":y}
        else:
            return {"x":x}

    def is2D(self):
        if "ycoordinates" in self.f:
            return True
        else:
            return False

    def getTrainLoss(self) -> np.ndarray:
        return self.f["train_loss"][:]

    def getTrainAcc (self):
        return self.f["train_acc"][:]
    
    def get_index(self,arr, value, type_of_coord=''):
        ind_arr = np.where(arr == value)[0]
        if ind_arr.size == 0:
            print(value,' not in ',type_of_coord,' coordinates')
            closest = np.argmin(np.abs(arr - value))
            print('Closest value is ', arr[closest])
            return closest
        if ind_arr.size > 1:
            print('Multiple values found, returning first index')
            return ind_arr[0]
        return ind_arr.item()

    def getTrainLoss_byCoords(self,x,y):
        x_ind = self.get_index(self.getCoordinates()['x'],x,type_of_coord='x')
        y_ind = self.get_index(self.getCoordinates()['y'],y,type_of_coord='y')
        return self.getTrainLoss()[x_ind,y_ind].item()
    
    def getTrainAcc_byCoords(self,x,y):
        x_ind = self.get_index(self.getCoordinates()['x'],x,type_of_coord='x')
        y_ind = self.get_index(self.getCoordinates()['y'],y,type_of_coord='y')
        return self.getTrainAcc()[x_ind,y_ind].item()

    def close(self):
        self.f.close()  
    
    def copy(self,dest=None):
        if dest is None:
            dst = "".join(self.path.split(".")[:-1]) + "_copy.hdf5"
        shutil.copyfile(self.path, dst)

    def increase_resolution(self, steps=2, dest=None, create=True):
        """
        Increase the resolution of the surface by a factor of steps.
        This is done by adding steps-1 points between each pair of points in the original surface.
        The boundary (min/max) of the coordinates remains the same.
        Newly added points in between the original points have a value of -1.
        Args:
            steps (int): factor by which to increase the resolution. Default is 2 which means doubleing the points.
            dest (str): destination path to save the new surface file. If None, it will be saved in the same directory as the original file with a new name reflecting the new dimensions of the surface file.
            create (bool): if True, create a new surface file with the increased resolution. If False, return the new path and file name without saving any data. (useful in multiprocessing where only one process can write to the file but a reference to the new file is needed)
        """
        steps += 1 # # steps = 1 means no increase in resolution
        assert steps > 1, "steps must be greater than 0. If set to 1 it will double the number of points in the surface."
        coords = self.getCoordinates()
        x = coords["x"]
        # New x coordinates: same min/max, more points
        new_x = np.linspace(x[0], x[-1], (len(x) - 1) * steps + 1)
        new_y = None

        if self.is2D():
            y = coords["y"]
            new_y = np.linspace(y[0], y[-1], (len(y) - 1) * steps + 1)
            new_loss = np.ones((len(new_x), len(new_y))) * -1
            new_acc = np.ones((len(new_x), len(new_y))) * -1
            for i in range(len(x)):
                for j in range(len(y)):
                    new_i = i * steps
                    new_j = j * steps
                    new_loss[new_i, new_j] = self.getTrainLoss()[i, j]
                    new_acc[new_i, new_j] = self.getTrainAcc()[i, j]
        else:
            new_loss = np.ones(len(new_x)) * -1
            new_acc = np.ones(len(new_x)) * -1
            for i in range(len(x)):
                new_i = i * steps
                new_loss[new_i] = self.getTrainLoss()[i]
                new_acc[new_i] = self.getTrainAcc()[i]

        if dest is None:
            dest = os.path.join(
                "".join(self.path.split("/")[:-1]),
                create_surface_file_name(new_x=new_x, new_y=new_y, file_name=self.path)
            )
        else:
            assert os.path.exists(dest), "Destination directory does not exist"
            dest = os.path.join(
                dest,
                create_surface_file_name(new_x=new_x, new_y=new_y, file_name=self.path.split("/")[-1])
            )

        if create:
            with h5py.File(dest, 'w') as new_h5:
                new_h5.create_dataset("dir_file", data=self.getDirFile())
                new_h5.create_dataset("train_loss", data=new_loss)
                new_h5.create_dataset("train_acc", data=new_acc)
                new_h5.create_dataset("xcoordinates", data=new_x)
                if self.is2D():
                    new_h5.create_dataset("ycoordinates", data=new_y)

            print("done \nincreased resolution of surface file ", self.path, " by a factor of ", str(steps), "\n   -> ", dest)
        return dest

    def extend_surface_file(self,steps,dest=None,create=True):

        coords = self.getCoordinates()
        x = coords["x"]
        steps_size = x[1] - x[0]
        new_x = [x[0] - steps_size*i for i in range(steps,0,-1)] + x.tolist() + [x[-1] + steps_size*i for i in range(1,steps+1)]
        if self.is2D():
            y = coords["y"]
            steps_size = y[1] - y[0]
            new_y = [y[0] - steps_size*i for i in range(steps,0,-1)] + y.tolist() + [y[-1] + steps_size*i for i in range(1,steps+1)]
        else:
            new_y = None
            
        
        loss = self.getTrainLoss()
        loss = np.pad(loss,((steps,steps),(steps,steps)),'constant', constant_values=(-1))
        acc = self.getTrainAcc()
        acc = np.pad(acc,((steps,steps),(steps,steps)),'constant', constant_values=(-1))

        if dest is None:
            dest = os.path.join("".join(self.path.split("/")[:-1]),create_surface_file_name(new_x=new_x, new_y=new_y, file_name=self.path.split("/")[-1]))
        else:
            assert os.path.exists(dest), "Destination directory does not exist"
            dest = os.path.join(dest,create_surface_file_name(new_x=new_x, new_y=new_y, file_name=self.path.split("/")[-1]))
                
        if create:
            f = h5py.File(dest, "a")
            f["dir_file"] = self.getDirFile()
            f["xcoordinates"] = new_x
            if self.is2D(): f["ycoordinates"] = new_y
            f["train_loss"] = loss
            f["train_acc"] = acc
            f.close()

            print("extended surface file ", self.path, " by ", str(steps), " steps")
            print("    -> saved in :", dest)
            print("total amount of coords to calculate: ", str((acc == -1).sum()))


        return dest

    def plot(self):
        # create 2 subplots for train_loss and train_acc. use plt.imshow to plot the 2D data. If it is 1D, use plt.plot
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))
        coords = self.getCoordinates()
        x = coords['x']
        ax1.set_xlabel('x')
        ax2.set_xlabel('x')
        ax1.set_title('Train Loss')
        ax2.set_title('Train Acc')
        # plot the train_loss
        if self.is2D():
            y = coords['y']
            im1 = ax1.imshow(self.getTrainLoss(), cmap='hot', interpolation='nearest', 
                             extent=[x[0], x[-1], y[0], y[-1]], aspect='auto', origin='lower')
            ax1.set_ylabel('y')
            # Set 5 ticks on each axis
            ax1.set_xticks(np.linspace(x[0], x[-1], 5))
            ax1.set_yticks(np.linspace(y[0], y[-1], 5))
            fig.colorbar(im1, ax=ax1, fraction=0.046, pad=0.04)
        else:
            ax1.plot(x, self.getTrainLoss())
            ax1.set_ylabel('Train Loss')
            ax1.set_xticks(np.linspace(x[0], x[-1], 5))
        # plot the train_acc
        if self.is2D():
            y = coords['y']
            im2 = ax2.imshow(self.getTrainAcc(), cmap='hot', interpolation='nearest', 
                             extent=[x[0], x[-1], y[0], y[-1]], aspect='auto', origin='lower')
            ax2.set_ylabel('y')
            ax2.set_xticks(np.linspace(x[0], x[-1], 5))
            ax2.set_yticks(np.linspace(y[0], y[-1], 5))
            fig.colorbar(im2, ax=ax2, fraction=0.046, pad=0.04)
        else:
            ax2.plot(x, self.getTrainAcc())
            ax2.set_ylabel('Train Acc')
            ax2.set_xticks(np.linspace(x[0], x[-1], 5))
        # plt.show()
        return fig, (ax1,ax2)

# not used
def modify_surface_file_path(path, step=None,min=None,max=None, is2D=True):
    if path[-5:] != ".hdf5" or path[-4:] != ".h5":
            path += ".h5"
    if step is not None:
        # find the numeral characters in original filename and replace with its double
        # e.g. surface_[0.00,1.00,10]x[0.00,1.00,10].hdf5 -> surface_[0.00,1.00,20]x[0.00,1.00,20].hdf5
        pattern_2 = r"\,\d+\]x" 
        pattern_1 = r"\,\d+\]\."
        s_adj_1 = re.sub(pattern_1, ","+str(int(re.search(pattern_1, path).group()[1:-2])*2)+"].", path)
        if is2D():
            save_path = re.sub(pattern_2, ","+str(int(re.search(pattern_2, s_adj_1).group()[1:-2])*3)+"]x", s_adj_1)
        else:
            save_path = s_adj_1
    if min is not None :
        # find the first number in the filename and replace with min
        pattern = r"\[.+?\,"
        save_path = re.sub(pattern, "["+str(min)+",", path)




    return save_path

# moved inside the class
def extend_surface_file(old_surf_path, steps, dest=None):
    old_surf = SurfaceFileHandler(old_surf_path)

    coords = old_surf.getCoordinates()
    x = coords["x"]
    steps_size = x[1] - x[0]
    new_x = [x[0] - steps_size*i for i in range(steps,0,-1)] + x.tolist() + [x[-1] + steps_size*i for i in range(1,steps+1)]
    if old_surf.is2D():
        y = coords["y"]
        steps_size = y[1] - y[0]
        new_y = [y[0] - steps_size*i for i in range(steps,0,-1)] + y.tolist() + [y[-1] + steps_size*i for i in range(1,steps+1)]
        
    
    loss = old_surf.getTrainLoss()
    loss = np.pad(loss,((steps,steps),(steps,steps)),'constant', constant_values=(-1))
    acc = old_surf.getTrainAcc()
    acc = np.pad(acc,((steps,steps),(steps,steps)),'constant', constant_values=(-1))
    
    if old_surf.is2D() :
        file_name = "surface_[%.2f,%.2f,%d]x[%.2f,%.2f,%d].hdf5" % (new_x[0],new_x[-1],len(new_x),new_y[0],new_y[-1],len(new_y))
    else:  file_name = "surface_[%.2f,%.2f,%d].hdf5" % (new_x[0],new_x[-1],len(new_x))
    print("extended surface file ", old_surf_path, " by ", str(steps), " steps")
    print("total amount of coords to calculate: ", str((acc == -1).sum()))

    new_surf_path = os.path.join(dest,file_name)
    f = h5py.File(new_surf_path, "a")
    f["dir_file"] = old_surf.getDirFile()
    f["xcoordinates"] = new_x
    if old_surf.is2D(): f["ycoordinates"] = new_y
    f["train_loss"] = loss
    f["train_acc"] = acc
    f.close()
    
    return new_surf_path

class DirFileHandler():
    """
    This class is used to handle the hdf5 files generated by the surface model.

    Args:
    - path (str): path to the hdf5 file

    Methods:
    - getDirFile: returns the directory of the file used to generate the hdf5 file
    - getCoordinates: returns the coordinates of the surface
    - getTrainLoss: returns the training loss
    - getTrainAcc: returns the training accuracy
    - __str__: prints the structure of the hdf5 file use print(DirFileHandler) to print the structure
    """
    def __init__(self,path):
        self.f = h5py.File(path, "r")
        self.path = path
    
    # with this method print(SurfaceFileHandler) will print the structure of the hdf5 file
    def __str__(self):
        print_hdf5(self.path)

    def getCoordinates(self):
        xdirection = read_list(self.f, 'xdirection')
        if 'ydirection' in self.f.keys():  # If this is a 2D plot
            ydirection = read_list(self.f, 'ydirection')
            return {"x":xdirection, "y":ydirection}
        else:
            return {"x":xdirection}
    
    def close(self):
        self.f.close()  
        