# RawNet3 example configuration
model: RawNet3
encoder_type: ECA
nOut: 256
sinc_stride: 10
max_frames: 300
batch_size: 32
eval_frames: 400
trainfunc: aamsoftmax
lr_decay: 0.75
weight_decay: 5e-05
max_seg_per_spk: 500
augment: True
save_path: exps/RawNet3_AAM

hdf5: True
train_list: data/SpeakerDataVox2.hdf5
test_interval: 2
initial_model: exps/RawNet3_AAM/epoch_20.pth
save_path: exps/RawNet3_AAM
log_file: True
